CREATE TABLE CONTACTS (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    firstname    VARCHAR(30),
    lastname    VARCHAR(30),
    telephone   VARCHAR(15),
    email         VARCHAR(30),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);